[tool.poetry]
name = "test"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.10"
requests = "*"

[tool.poetry.dev-dependencies]
pytest-cov = "*"
pytest = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"